//! The Phase-4 player-pool lifecycle (`TRANSFER_MODEL.md` §8): the two ends
//! development alone leaves untouched. Left to itself the pool only drains
//! (aging, and once P4.5 can release players, unsigned attrition) or turns
//! geriatric — either way `TRANSFER_MODEL.md` §11's decade-long metrics would
//! measure a confounded pool, not market dynamics.
//!
//! **Youth intake** (§8.1): an annual cohort per club at the summer window,
//! reusing `worldgen::gen_player` with a tight 16-18 age band. Quality
//! anchors on the club's `reputation` scaled by its `coaching_milli`
//! multiplier — the second genuine consumer of the academy lever,
//! `worldgen::resolve_coaching` being the first.
//!
//! **Retirement** (§8.2): age ≥ `min_retirement_age` and either a best-role
//! CA below a league-relevance floor, or a full season spent unsigned.
//! Retired players stay in `World.players` (the log still references them in
//! historical `MatchPlayed` XIs) but leave every roster; `Player::retired` is
//! the marker every other consumer (`club_ai::observe`'s candidate filter,
//! `development::tick_changes`'s implicit exclusion via roster absence) can
//! check.
//!
//! Both fire at the same summer-window boundary `commands::transfer_window_events`
//! already fires the market on — one more emitter beside `dev_ticks_between`
//! and `market::resolve_window`, not a new tick mechanism.

use crate::development::DevKnobs;
use crate::event::Event;
use crate::rng::{Rng, derive_stream};
use crate::worldgen::gen_player;
use fforge_domain::{
    GameDate, Player, PlayerId, ROLE_WEIGHTS, Role, World, best_role, date::DAYS_PER_YEAR,
};
use std::collections::BTreeMap;

/// Tag namespace for the per-window youth-intake RNG stream
/// (`rng::derive_stream`), following the `TRANSFER_MODEL.md` §5 convention
/// (`"TRAN"`/`"FINA"`/`"YOUT"`). The window index is OR'd into the low bits,
/// so every summer window draws an independent stream.
pub const YOUTH_STREAM_NS: u64 = 0x594F_5554_0000_0000; // "YOUT"

/// The pool's own knob table (`TRANSFER_MODEL.md` §8): a plausibility-picked
/// starting point, sibling of `DevKnobs`/`ValueKnobs`/`UtilityKnobs`/
/// `MarketKnobs`/`FinanceKnobs` — a §11-harness re-fit target like the rest
/// of them (this task's scope fence is `DevKnobs` specifically, not this
/// brand-new table).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PoolKnobs {
    /// Youths generated per club per summer window (§8.1).
    pub youth_cohort_size: usize,
    /// §8.2: a player younger than this never retires, regardless of CA or
    /// contract status.
    pub min_retirement_age: i32,
    /// §8.2's "league-relevance floor": a ≥-`min_retirement_age` player whose
    /// best-role CA has fallen below this retires outright.
    pub relevance_floor: u8,
}

impl Default for PoolKnobs {
    fn default() -> Self {
        PoolKnobs {
            youth_cohort_size: 2,
            min_retirement_age: 34,
            // Picked empirically against a real 15-season run, not a low
            // "obviously irrelevant" number: `DEVELOPMENT_MODEL.md`'s own
            // aging law lets mental/technical composites plateau rather than
            // crash (`career_arc`'s "physicals decline hard while mental
            // holds"), so a 34+ player's best-role CA routinely plateaus in
            // the high 50s-60s and never revisits a low floor — a `45` floor
            // left most veterans immortal, filling every squad and blocking
            // intake, and league mean age climbed past 37 inside 15 seasons.
            // `62` sits inside that plateau band, so a real fraction of every
            // aging cohort crosses below it each window — the release valve
            // `TRANSFER_MODEL.md` §8 needs opposite intake to actually close
            // the loop, not just a floor that is technically implemented.
            relevance_floor: 62,
        }
    }
}

/// One club's youth cohort (§8.1): up to `knobs.youth_cohort_size` fresh
/// 16-18s (fewer if `cohort_size` was already capped by the caller to the
/// club's roster headroom — see `summer_pool_events`), generated by reusing
/// `worldgen::gen_player`. `quality` anchors on the club's `reputation` —
/// the same scale `gen_player`'s `club_quality` argument already expects,
/// since `worldgen::resolve_reputation` derives reputation from that very
/// quality anchor — scaled by the club's coaching multiplier, so a
/// well-coached academy turns out a better cohort than an
/// identically-reputable club with a poor one. `next_id` is threaded through
/// and advanced so consecutive clubs in the same window never collide.
fn youth_cohort(
    rng: &mut Rng,
    reputation: u8,
    coaching_milli: u16,
    cohort_size: usize,
    next_id: &mut u32,
    today: GameDate,
    dev_knobs: &DevKnobs,
) -> Vec<Player> {
    let quality = reputation as f64 * (coaching_milli as f64 / 1000.0);
    (0..cohort_size)
        .map(|_| {
            let role = Role::ALL[rng.below(Role::ALL.len() as u32) as usize];
            let age = 16 + rng.below(3) as i32; // §8.1: a 16-18 age band
            let id = PlayerId(*next_id);
            *next_id += 1;
            gen_player(rng, id, role, quality, age, today, dev_knobs)
        })
        .collect()
}

/// Every player who retires this summer window (§8.2): age ≥
/// `min_retirement_age` and (best-role CA below `relevance_floor` or gone a
/// full season unsigned). `unsigned_since` is `GameState`'s bookkeeping of
/// the date each currently contract-less player last lost his contract (set
/// on `PlayerReleased`, cleared on re-signing) — "a full season" reads as one
/// sim-year elapsed since then. Already-retired players are excluded so a
/// re-run never emits a second `PlayerRetired` for the same player.
fn retirements(
    world: &World,
    today: GameDate,
    unsigned_since: &BTreeMap<PlayerId, GameDate>,
    knobs: &PoolKnobs,
) -> Vec<PlayerId> {
    world
        .players
        .values()
        .filter(|p| !p.retired && p.age(today) >= knobs.min_retirement_age)
        .filter(|p| {
            let (_, ca) = best_role(&p.attributes, &ROLE_WEIGHTS);
            let below_floor = ca < knobs.relevance_floor;
            let full_season_unsigned = p.contract.is_none()
                && unsigned_since
                    .get(&p.id)
                    .is_some_and(|since| today.days - since.days >= DAYS_PER_YEAR);
            below_floor || full_season_unsigned
        })
        .map(|p| p.id)
        .collect()
}

/// The summer window's pool events (`TRANSFER_MODEL.md` §8): one
/// `YouthIntake` per club with headroom (`World.clubs` order —
/// deterministic), then every qualifying `PlayerRetired` (`World.players`
/// order). Pure function of its inputs; its only randomness is
/// `derive_stream(seed, YOUTH_STREAM_NS | window_index)`, drawn in club-id
/// order, so replay reproduces an identical cohort set — a club's headroom
/// (and therefore how much of the stream it consumes) is itself fully
/// determined by prior, already-deterministic world state, so branching on
/// it introduces no nondeterminism. Retirement itself draws no RNG (a pure
/// filter), so it never perturbs the youth stream's position.
///
/// **`squad_max` caps intake to roster headroom.** §6's hard squad-bound
/// stabilizer (`club_ai::UtilityPolicy`'s `squad_max`, passed in rather than
/// re-encoded — the same "one source of truth" discipline `SQUAD_TEMPLATE`
/// gets) already stops the market from *buying* a club past it; without the
/// same cap here, intake alone can walk a club straight through it whenever
/// the market can't find buyers fast enough to absorb the cohort — a squad
/// only grows, never sheds, once nobody wants what's on offer. A club
/// already at or above `squad_max` gets no cohort at all this window.
#[allow(clippy::too_many_arguments)]
pub fn summer_pool_events(
    world: &World,
    today: GameDate,
    seed: u64,
    window_index: u64,
    unsigned_since: &BTreeMap<PlayerId, GameDate>,
    dev_knobs: &DevKnobs,
    knobs: &PoolKnobs,
    squad_max: usize,
) -> Vec<Event> {
    let mut rng = derive_stream(seed, YOUTH_STREAM_NS | window_index);
    let mut next_id = world.players.keys().next_back().map_or(0, |id| id.0 + 1);

    let mut events = Vec::with_capacity(world.clubs.len() + 4);
    for (&club_id, club) in &world.clubs {
        let room = squad_max.saturating_sub(club.players.len());
        let cohort_size = knobs.youth_cohort_size.min(room);
        let players = youth_cohort(
            &mut rng,
            club.reputation,
            club.coaching_milli,
            cohort_size,
            &mut next_id,
            today,
            dev_knobs,
        );
        if !players.is_empty() {
            events.push(Event::YouthIntake {
                date: today,
                club: club_id,
                players,
            });
        }
    }

    for player in retirements(world, today, unsigned_since, knobs) {
        events.push(Event::PlayerRetired {
            date: today,
            player,
        });
    }

    events
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::worldgen::{WorldGenConfig, generate};
    use fforge_domain::ClubId;

    const TODAY: GameDate = GameDate { days: 2030 * 365 };
    /// A generous cap so ordinary worldgen-sized squads never hit it — the
    /// squad_max-capping tests below set it explicitly instead.
    const SQUAD_MAX: usize = 30;

    #[test]
    fn youth_intake_adds_one_cohort_per_club_with_fresh_ids_in_the_16_to_18_band() {
        let cfg = WorldGenConfig {
            num_clubs: 4,
            ..Default::default()
        };
        let (world, _schedule, start) = generate(13, &cfg);
        let max_existing = *world.players.keys().next_back().unwrap();

        let events = summer_pool_events(
            &world,
            start,
            13,
            0,
            &BTreeMap::new(),
            &DevKnobs::default(),
            &PoolKnobs::default(),
            SQUAD_MAX,
        );

        let intakes: Vec<&Event> = events
            .iter()
            .filter(|e| matches!(e, Event::YouthIntake { .. }))
            .collect();
        assert_eq!(intakes.len(), world.clubs.len(), "one YouthIntake per club");

        for e in &intakes {
            let Event::YouthIntake { players, .. } = e else {
                unreachable!()
            };
            assert_eq!(players.len(), PoolKnobs::default().youth_cohort_size);
            for p in players {
                assert!(
                    p.id > max_existing,
                    "youth id must not collide with an existing player"
                );
                let age = p.age(start);
                assert!((16..=18).contains(&age), "youth age {age} outside 16-18");
                assert!(
                    p.contract.is_some(),
                    "an intake youth is signed to his club"
                );
            }
        }

        // No id collisions across clubs' cohorts either.
        let mut ids: Vec<PlayerId> = intakes
            .iter()
            .flat_map(|e| match e {
                Event::YouthIntake { players, .. } => {
                    players.iter().map(|p| p.id).collect::<Vec<_>>()
                }
                _ => unreachable!(),
            })
            .collect();
        let before = ids.len();
        ids.sort();
        ids.dedup();
        assert_eq!(ids.len(), before, "no duplicate ids across cohorts");
    }

    #[test]
    fn intake_is_capped_to_squad_max_headroom() {
        // §6's hard squad-bound stabilizer must also gate intake (this
        // task's own bug fix, caught by `pool_size_stays_bounded_across_fifteen_seasons`):
        // a club already at the cap gets no cohort at all; a club with only
        // one slot of room gets a one-player cohort, never the full
        // `youth_cohort_size`.
        let cfg = WorldGenConfig {
            num_clubs: 4,
            ..Default::default()
        };
        let (mut world, _schedule, start) = generate(31, &cfg);
        let ids: Vec<ClubId> = world.clubs.keys().copied().collect();
        let (full, one_room, plenty_room) = (ids[0], ids[1], ids[2]);
        let squad_max = 26usize;

        let template: Vec<PlayerId> = world.club(plenty_room).players.clone();
        // Pad `full` up to the cap exactly, and `one_room` to one below it,
        // by borrowing ids from a template roster (values don't matter here,
        // only roster length).
        let mut extra = 1000u32;
        while world.club(full).players.len() < squad_max {
            let pid = PlayerId(extra);
            extra += 1;
            let mut p = world.player(template[0]).clone();
            p.id = pid;
            world.players.insert(pid, p);
            world.clubs.get_mut(&full).unwrap().players.push(pid);
        }
        while world.club(one_room).players.len() < squad_max - 1 {
            let pid = PlayerId(extra);
            extra += 1;
            let mut p = world.player(template[0]).clone();
            p.id = pid;
            world.players.insert(pid, p);
            world.clubs.get_mut(&one_room).unwrap().players.push(pid);
        }

        let events = summer_pool_events(
            &world,
            start,
            31,
            0,
            &BTreeMap::new(),
            &DevKnobs::default(),
            &PoolKnobs::default(),
            squad_max,
        );

        let cohort_of = |club: ClubId| -> usize {
            events
                .iter()
                .filter_map(|e| match e {
                    Event::YouthIntake {
                        club: c, players, ..
                    } if *c == club => Some(players.len()),
                    _ => None,
                })
                .next()
                .unwrap_or(0)
        };

        assert_eq!(cohort_of(full), 0, "a club at squad_max must get no cohort");
        assert_eq!(
            cohort_of(one_room),
            1,
            "a club one slot under squad_max must get a one-player cohort"
        );
        assert_eq!(
            cohort_of(plenty_room),
            PoolKnobs::default().youth_cohort_size,
            "a club with plenty of room must get the full cohort"
        );
    }

    #[test]
    fn better_coached_reputation_matched_clubs_produce_better_cohorts_on_average() {
        // The academy lever (§8.1): at equal reputation, a higher
        // coaching_milli must skew the cohort's quality up, on average over
        // many windows (a single 2-player cohort is too small to test
        // per-window).
        let cfg = WorldGenConfig {
            num_clubs: 2,
            ..Default::default()
        };
        let (mut world, _schedule, start) = generate(4, &cfg);
        let ids: Vec<ClubId> = world.clubs.keys().copied().collect();
        let (lo, hi) = (ids[0], ids[1]);
        world.clubs.get_mut(&lo).unwrap().reputation = 60;
        world.clubs.get_mut(&hi).unwrap().reputation = 60;
        world.clubs.get_mut(&lo).unwrap().coaching_milli = 850;
        world.clubs.get_mut(&hi).unwrap().coaching_milli = 1150;

        let knobs = PoolKnobs {
            youth_cohort_size: 6,
            ..PoolKnobs::default()
        };
        let mut lo_sum = 0f64;
        let mut hi_sum = 0f64;
        let mut n = 0f64;
        for seed in 0..30u64 {
            let events = summer_pool_events(
                &world,
                start,
                seed,
                0,
                &BTreeMap::new(),
                &DevKnobs::default(),
                &knobs,
                SQUAD_MAX,
            );
            for e in &events {
                let Event::YouthIntake { club, players, .. } = e else {
                    continue;
                };
                let mean_ca: f64 = players
                    .iter()
                    .map(|p| best_role(&p.attributes, &ROLE_WEIGHTS).1 as f64)
                    .sum::<f64>()
                    / players.len() as f64;
                if *club == lo {
                    lo_sum += mean_ca;
                } else {
                    hi_sum += mean_ca;
                }
            }
            n += 1.0;
        }
        assert!(
            hi_sum / n > lo_sum / n,
            "better coaching at equal reputation should raise mean youth CA: lo {} vs hi {}",
            lo_sum / n,
            hi_sum / n
        );
    }

    #[test]
    fn a_below_floor_veteran_retires() {
        let cfg = WorldGenConfig {
            num_clubs: 2,
            ..Default::default()
        };
        let (mut world, _schedule, _start) = generate(6, &cfg);
        let club = world.competition.clubs[0];
        let pid = world.club(club).players[0];
        {
            let p = world.players.get_mut(&pid).unwrap();
            p.birth = TODAY.add_days(-36 * DAYS_PER_YEAR);
            for a in fforge_domain::Attribute::ALL {
                p.attributes.set(a, 5);
            }
        }

        let retiring = retirements(&world, TODAY, &BTreeMap::new(), &PoolKnobs::default());
        assert!(retiring.contains(&pid));
    }

    #[test]
    fn a_young_below_floor_player_does_not_retire() {
        let cfg = WorldGenConfig {
            num_clubs: 2,
            ..Default::default()
        };
        let (mut world, _schedule, _start) = generate(6, &cfg);
        let club = world.competition.clubs[0];
        let pid = world.club(club).players[0];
        {
            let p = world.players.get_mut(&pid).unwrap();
            p.birth = TODAY.add_days(-22 * DAYS_PER_YEAR);
            for a in fforge_domain::Attribute::ALL {
                p.attributes.set(a, 5);
            }
        }

        let retiring = retirements(&world, TODAY, &BTreeMap::new(), &PoolKnobs::default());
        assert!(!retiring.contains(&pid));
    }

    #[test]
    fn a_veteran_unsigned_a_full_season_retires_even_with_decent_ca() {
        let cfg = WorldGenConfig {
            num_clubs: 2,
            ..Default::default()
        };
        let (mut world, _schedule, _start) = generate(6, &cfg);
        let club = world.competition.clubs[0];
        let pid = world.club(club).players[0];
        {
            let p = world.players.get_mut(&pid).unwrap();
            p.birth = TODAY.add_days(-35 * DAYS_PER_YEAR);
            p.contract = None;
        }
        // Not on any roster: a released free agent (`World.clubs` sole index).
        world
            .clubs
            .get_mut(&club)
            .unwrap()
            .players
            .retain(|&p| p != pid);

        let mut unsigned_since = BTreeMap::new();
        unsigned_since.insert(pid, TODAY.add_days(-DAYS_PER_YEAR - 1));

        let retiring = retirements(&world, TODAY, &unsigned_since, &PoolKnobs::default());
        assert!(retiring.contains(&pid));
    }

    #[test]
    fn a_veteran_unsigned_less_than_a_season_does_not_retire_on_that_ground_alone() {
        let cfg = WorldGenConfig {
            num_clubs: 2,
            ..Default::default()
        };
        let (mut world, _schedule, _start) = generate(6, &cfg);
        let club = world.competition.clubs[0];
        let pid = world.club(club).players[0];
        {
            let p = world.players.get_mut(&pid).unwrap();
            p.birth = TODAY.add_days(-35 * DAYS_PER_YEAR);
            p.contract = None;
            // Keep CA comfortably above the relevance floor.
            for a in fforge_domain::Attribute::ALL {
                p.attributes.set(a, 80);
            }
        }
        world
            .clubs
            .get_mut(&club)
            .unwrap()
            .players
            .retain(|&p| p != pid);

        let mut unsigned_since = BTreeMap::new();
        unsigned_since.insert(pid, TODAY.add_days(-30));

        let retiring = retirements(&world, TODAY, &unsigned_since, &PoolKnobs::default());
        assert!(!retiring.contains(&pid));
    }

    #[test]
    fn already_retired_players_are_never_retired_twice() {
        let cfg = WorldGenConfig {
            num_clubs: 2,
            ..Default::default()
        };
        let (mut world, _schedule, _start) = generate(6, &cfg);
        let pid = world
            .competition
            .clubs
            .first()
            .map(|&c| world.club(c).players[0])
            .unwrap();
        {
            let p = world.players.get_mut(&pid).unwrap();
            p.birth = TODAY.add_days(-40 * DAYS_PER_YEAR);
            p.retired = true;
            for a in fforge_domain::Attribute::ALL {
                p.attributes.set(a, 5);
            }
        }

        let retiring = retirements(&world, TODAY, &BTreeMap::new(), &PoolKnobs::default());
        assert!(!retiring.contains(&pid));
    }

    #[test]
    fn same_seed_yields_an_identical_pool_outcome() {
        let cfg = WorldGenConfig {
            num_clubs: 6,
            ..Default::default()
        };
        let (world, _schedule, start) = generate(9, &cfg);
        let a = summer_pool_events(
            &world,
            start,
            9,
            0,
            &BTreeMap::new(),
            &DevKnobs::default(),
            &PoolKnobs::default(),
            SQUAD_MAX,
        );
        let b = summer_pool_events(
            &world,
            start,
            9,
            0,
            &BTreeMap::new(),
            &DevKnobs::default(),
            &PoolKnobs::default(),
            SQUAD_MAX,
        );
        assert_eq!(
            a, b,
            "identical inputs must yield an identical pool outcome"
        );
    }

    /// Drive a real `Session` (worldgen → AI lineups → match engine →
    /// monthly development/finance/market/pool ticks) across `seasons` full
    /// seasons — the same real-pipeline discipline `career_arc::trace_seed`
    /// uses, since a synthetic cohort can't exercise the summer-window
    /// scheduling this task is actually about.
    fn run_seasons(seed: u64, seasons: usize) -> crate::Session {
        let log = crate::new_game(seed, &WorldGenConfig::default(), ClubId(0));
        let mut session = crate::Session::from_events(log, &mut []);
        for s in 0..seasons {
            while !session.state.season_over() {
                session
                    .execute(crate::Command::AdvanceMatchday, &mut [])
                    .expect("advance matchday");
            }
            if s + 1 < seasons {
                session
                    .execute(crate::Command::StartNextSeason, &mut [])
                    .expect("start next season");
            }
        }
        session
    }

    fn active_players(world: &World) -> Vec<&Player> {
        world.players.values().filter(|p| !p.retired).collect()
    }

    fn mean_age(world: &World, today: GameDate) -> f64 {
        let active = active_players(world);
        active.iter().map(|p| p.age(today) as f64).sum::<f64>() / active.len() as f64
    }

    /// `TRANSFER_MODEL.md` §11: "League mean age ... stable" — the whole
    /// reason this task exists (P4.7's decade-long metrics measure a
    /// draining or geriatric pool otherwise). Pooled over a couple of seeds
    /// (`career_arc`'s "treat multi-seed pooling as a project-wide harness
    /// invariant"), a deliberately wide sanity band per the same doc's §11
    /// "wide bands, gross-regression tripwires — not fit gates": it must
    /// neither drain toward a geriatric squad (youth intake too small/absent)
    /// nor crash toward academy age (intake wildly outpacing retirement).
    #[test]
    fn league_mean_age_is_stable_across_fifteen_seasons() {
        let seasons = 15;
        for seed in [1u64, 2u64] {
            let log = crate::new_game(seed, &WorldGenConfig::default(), ClubId(0));
            let mut session = crate::Session::from_events(log, &mut []);
            let start_mean = mean_age(&session.state.world, session.state.date);

            for s in 0..seasons {
                while !session.state.season_over() {
                    session
                        .execute(crate::Command::AdvanceMatchday, &mut [])
                        .expect("advance matchday");
                }
                if s + 1 < seasons {
                    session
                        .execute(crate::Command::StartNextSeason, &mut [])
                        .expect("start next season");
                }
            }

            let end_mean = mean_age(&session.state.world, session.state.date);
            assert!(
                (18.0..=32.0).contains(&end_mean),
                "seed {seed}: mean age {end_mean:.2} drifted outside a believable band after {seasons} seasons"
            );
            assert!(
                (end_mean - start_mean).abs() < 6.0,
                "seed {seed}: mean age drifted from {start_mean:.2} to {end_mean:.2} over {seasons} seasons"
            );
        }
    }

    /// `TRANSFER_MODEL.md` §11: "squad sizes ... all in [18,30]" plus the
    /// pool-as-a-whole not exploding or collapsing — the second half of
    /// closing the loop at both ends. Every club's roster is checked against
    /// the market's own hard stabilizer bounds (`UtilityKnobs::squad_min`/
    /// `squad_max`); the league-wide active (non-retired) population is
    /// checked against a wide multiple of its starting size, wide enough to
    /// tolerate the §12.3-flagged free-agent-pool drift without being a fit
    /// gate.
    #[test]
    fn pool_size_stays_bounded_across_fifteen_seasons() {
        let start_active = {
            let (world, _s, _d) = generate(3, &WorldGenConfig::default());
            active_players(&world).len()
        };

        let session = run_seasons(3, 15);
        let world = &session.state.world;

        let uk = crate::UtilityKnobs::default();
        for club in world.clubs.values() {
            assert!(
                (uk.squad_min..=uk.squad_max).contains(&club.players.len()),
                "{} ended with {} players, outside [{}, {}]",
                club.name,
                club.players.len(),
                uk.squad_min,
                uk.squad_max
            );
        }

        let end_active = active_players(world).len();
        assert!(
            end_active >= start_active / 2 && end_active <= start_active * 3,
            "active pool size drifted from {start_active} to {end_active} over 15 seasons — \
             outside a wide [0.5x, 3x] sanity band"
        );
    }

    /// `TRANSFER_MODEL.md` §8.2: a retired player "leaves every roster and
    /// [is] excluded from ... the market." Scans the whole log chronologically
    /// (append-only, so log order is calendar order): once a `PlayerRetired`
    /// is seen for a player, that id must never again appear in a
    /// `MatchPlayed` XI (a lineup) or as a `TransferCompleted` party (a bid
    /// that won).
    #[test]
    fn retired_players_never_appear_in_a_lineup_or_a_completed_transfer_again() {
        let session = run_seasons(5, 15);
        let mut retired: std::collections::BTreeSet<PlayerId> = std::collections::BTreeSet::new();
        let mut checked_any = false;

        for event in &session.log {
            match event {
                Event::PlayerRetired { player, .. } => {
                    retired.insert(*player);
                }
                Event::MatchPlayed {
                    home_xi, away_xi, ..
                } => {
                    for &pid in home_xi.iter().chain(away_xi) {
                        assert!(
                            !retired.contains(&pid),
                            "retired player {pid:?} appeared in a MatchPlayed XI"
                        );
                        checked_any = true;
                    }
                }
                Event::TransferCompleted { player, .. } => {
                    assert!(
                        !retired.contains(player),
                        "retired player {player:?} appeared in a completed transfer"
                    );
                    checked_any = true;
                }
                _ => {}
            }
        }

        assert!(
            !retired.is_empty(),
            "no PlayerRetired at all over 15 seasons — retirement never fired"
        );
        assert!(
            checked_any,
            "no MatchPlayed/TransferCompleted events to check at all"
        );
    }
}
